# Numpy 

In [1]:
print("start abhi")

start abhi


In [2]:
import numpy as np

In [15]:
myarr=np.array([2,3,45,6] , np.int8)
myarr


array([ 2,  3, 45,  6], dtype=int8)

In [40]:
myarr=np.array([3,3,45,52,])
myarr[1]

np.int64(3)

In [43]:
myarr=np.array([[3,3,45,52,]])
myarr[0,3]

np.int64(52)

In [47]:
myarr[0,3]=89
myarr

array([[ 3,  3, 45, 89]])

In [62]:
newarray=np.array([[1,2,3],[4,5,6],[7,8,9],])
newarray



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
newarray.dtype

dtype('int64')

In [61]:
newarray.shape

(3, 3)

In [63]:
newarray.size

9

In [89]:
rng=np.arange(10)
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])